### ISSUE TITLE
[Définir les caractéristiques] Je ne peux pas mettre les caractériques que je veux.

### ISSUE THREAD

**Issue by tienslebienz** [Okazari/MyVirtualStoryBook#55]
Je souhaite mettre mes caractériques comme suis:
**A**dresse 7
**V**igueur 8
**I**ngéniosité 9

Si je tente de répartir mes points dans l'ordre A, V, I, je ne peux aller au bout de la répartition, quand je suis à A7, V8, I8, l'interface ne propose que d'augmenter l'adresse.

Contournement: faire les choix en sens inverse : IVA

**Comment by david-dasilva** [comment]
J'ai le même problème sur l'histoire **Interlude** : 
choix de départ : 
- Maitre d'arme
- Eloquence
- Acrobatie
- Connaissance
- Robustesse

Je selectionne Maitre d'armes, les choix restants deviennent : 
- Eloquence
- Acrobatie
- Robustesse

Il manque **Connaissance**.

**Comment by RQMplays** [comment]
Ces deux problèmes ont été réglé, n'hésitez pas à aller tester, et n'oubliez pas de recréer une nouvelle partie sinon vous aurez toujours l'ancienne version des livres !

Merci de continuer à remonter tout autre bug que vous rencontrerez,
Je ne promets pas par contre de m'occuper de toute les incohérences dans les livres de démonstrations car ce sont les oeuvres des auteurs,

cordialement.
