### ISSUE TITLE
La redirection vers le formulaire d'authentification fait un history replace au lieu d'un push

### ISSUE THREAD

**Issue by Okazari** [Okazari/MyVirtualStoryBook#59]

**Comment by RQMplays** [comment]
Le replace remplace la page sur laquelle l'utilisateur n'a pas encore les droits d'accès.
Si on fait un push, l'utilisateur ne peut plus refaire de retour-arrière pour revenir à la page précédente, il se retrouve sur la page auquel il n'a pas accès et se revoit redirigé, il est donc bloqué.

Sauf si tu as une manière de faire, je pense que c'est le comportement voulu !
Close issue when approved :D
